bourki/urls.py
from django.urls import path
from .views import  *
from bourki import  views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


app_name="bourki"

urlpatterns = [
    path("",IndexView.as_view(),name="home"),  
    path("about/",AboutView,name="about"),
    path("contact/",Contactus.as_view(),name="contact"),
    path("thanks/",thanks.as_view(),name="thanks"),
    path("Projectdetail/",Projectdetail.as_view(),name="projectdetail"),
    path("vlogs/",VediosView.as_view(),name="vedio"),
    path("blogs/",BlogsView.as_view(),name="blogs"),
    path("portfolio/",PortfolioView.as_view(),name="portfolio"),
    path("blogdetail/<slug:slug>/",DlogdetailView.as_view(),name="blogdetail"),
    path("vlogdetaildetail/<slug:slug>/",VediodetaildetailView.as_view(),name="vlogdetaildetail"),
    
    # path("tours_detail/<slug:slug>/",DetailtoursView.as_view(),name="detailtours"),
    # path("test/",views.TestView,name='test'),
    # path("about/",AboutusView.as_view(),name='aboutus'),
    # path("contactus/",ContactView.as_view(),name='contactus'),
    # path("buildtour/", BuildtourtView.as_view(), name='buildtour'),
    # path("faq/",FaqView.as_view(),name="faqs"),
    # path("specialtourdetail/<slug:slug>/",Specialdetailview.as_view(),name='specialdetail'),
    # path("specialtours/",SpecialoffrsViews.as_view(),name="specilaoffre"),
    # path("blogdetail/<slug:slug>/",Blogdetail.as_view(),name="blogdetail"),
    # path("Thanks/",ThankstView.as_view(),name="Thanks"),
    # path("searchblog/",SearchblogView.as_view(),name="searchblog"),
    # path("search/",SearchView.as_view(),name="search"),
    # path("hoteldetail/<slug:slug>/", HoteldetailView.as_view(), name='hotelsdetail'),
    # path('category/<category>/', views.CatListView.as_view(), name='category'),
    # path("categoryblog/<categoryblog>/",CatblogListView.as_view(),name="categoryblog"),
    # path("hotels/",AllhotelsView.as_view(),name="allhotels"),
    # path("vlogs/",VlogsView.as_view(),name="vlogs"),


 ]#+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

bourkidev/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls import include,url
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from bourki.sitemaps import StaticViewSitemap
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sites.models import  Site
from  django.conf.urls import  handler500
sitemaps ={
    'sitemap':StaticViewSitemap
}
urlpatterns = [
    path('jet/',include("jet.urls")),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',include("bourki.urls")),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT,}),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap')
 ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "bourki.views.error_404"

handler504 = "bourki.views.error_500"

templates/blog.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Kross | Portfolio Template</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">


</head>

<body>
  



<!-- page title -->
<section class="page-title bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="text-white font-tertiary">Blogs</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{% static 'images/illustrations/page-title.png' %}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{% static 'images/illustrations/dots-cyan.png' %}" alt="illustrations" class="bg-shape-3">
  <img src="{% static 'images/illustrations/new.png' %}" alt="illustrations" class="bg-shape-4">
  <img src="{% static 'images/illustrations/leaf-yellow.png' %}" alt="illustrations" class="bg-shape-5">
  <img src="{% static 'images/illustrations/dots-group-cyan.png' %}" alt="illustrations" class="bg-shape-6">
  <img src="{% static 'images/illustrations/leaf-cyan-lg.png' %}" alt="illustrations" class="bg-shape-7">
</section>
<!-- /page title -->

<!-- blog -->
<section class="section">
  <div class="container">
    <div class="row">


      {% for blog in blogs %}
        <div class="col-lg-4 col-sm-6 mb-4">
          <article class="card shadow">
            <img class="rounded card-img-top" src="{{blog.image.url}}" style="height:300px;" alt="post-thumb">
            <div class="card-body">
              <h4 class="card-title"><a class="text-dark" href="blog-single.html">{{blog.title}}</a>
              </h4>
              <p class="cars-text">{{blog.small_description|truncatewords:10}}</p>
              <a href="{% url 'bourki:blogdetail' blog.slug %}" class="btn btn-xs btn-primary">Read More</a>
            </div>
          </article>
        </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- /blog -->

<!-- clients -->
<section class="section bg-light">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">My Clients</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="client-logo-slider d-flex align-items-center">
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-1.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-2.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-3.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-4.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-5.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-1.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-2.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-3.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-4.pngg' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-5.png' %}" alt="client-logo"></a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /clients -->

<!-- contact -->
<section class="section section-on-footer" data-background="{% static 'images/backgrounds/bg-dots.png' %}">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">Contact Info</h2>
      </div>
      <div class="col-lg-8 mx-auto">
        <div class="bg-white rounded text-center p-5 shadow-down">
          <h4 class="mb-80">Contact Form</h4>
          <form action="#" class="row">
            <div class="col-md-6">
              <input type="text" id="name" name="name" placeholder="Full Name" class="form-control px-0 mb-4">
            </div>
            <div class="col-md-6">
              <input type="email" id="email" name="email" placeholder="Email Address" class="form-control px-0 mb-4">
            </div>
            <div class="col-12">
              <textarea name="message" id="message" class="form-control px-0 mb-4"
                placeholder="Type Message Here"></textarea>
            </div>
            <div class="col-lg-6 col-10 mx-auto">
              <button class="btn btn-primary w-100">send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /contact -->



<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- filter -->
<script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

{% endblock %}

templates/blogdetail.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Kross | Portfolio Template</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="plugins/bootstrap/bootstrap.min.css">
  <!-- slick slider -->
  <link rel="stylesheet" href="plugins/slick/slick.css">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="plugins/themify-icons/themify-icons.css">

  <!-- Main Stylesheet -->
  <link href="css/style.css" rel="stylesheet">
  
  <!--Favicon-->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
  <link rel="icon" href="images/favicon.ico" type="image/x-icon">

</head>

<body>
  


<!-- page title -->
<section class="page-title bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="text-white font-tertiary">Blogs</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{% static 'images/illustrations/page-title.png' %}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{% static 'images/illustrations/dots-cyan.png' %}" alt="illustrations" class="bg-shape-3">
  <img style="width: 150px;height: 150px;" src="{% static 'images/illustrations/Nerd-amico.png' %}" alt="illustrations" class="bg-shape-4">
  <img src="{% static 'images/illustrations/leaf-yellow.png' %}" alt="illustrations" class="bg-shape-5">
  <img src="{% static 'images/illustrations/dots-group-cyan.png' %}" alt="illustrations" class="bg-shape-6">
  <img src="{% static 'images/illustrations/leaf-cyan-lg.png' %}" alt="illustrations" class="bg-shape-7">
</section>
<!-- /page title -->

<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3 style="color: blueviolet;" class="font-tertiary mb-5">{{blog.title}}</h3>
        <p class="font-secondary">{{blog.date}} by <span class="text-primary">BourkiMdev</span
            class="text-primary"> on <span>DEV WEB</span></p>
        <div class="content">
         <br>

         {{blog.description|safe}}
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
       {% with blog.comments.count as total_comments %}
        <h4 class="font-weight-bold mb-3">Comments {{total_comments}}</h4>
       {% endwith %}
        {% if not blog.comments.all  %}
        <h5>no comments yet...</h5>

        {% else %}
    
        <div class="bg-gray p-5 mb-4">

          {% for coment in blog.comments.all %}
          <div class="media border-bottom py-4">
            <img src="{% static 'images/user-1.jpg' %}" class="img-fluid align-self-start rounded-circle mr-3" alt="">
            <div class="media-body">

              <h5 class="mt-0">{{coment.First_name}} {{coment.Last_name}}.</h5>
              <p>{{coment.created_at}}</p>
              <p>{{coment.Comment}}</p>
           
            
            </div>
          </div>
           {% endfor %}
           {% endif %}
          
        
        </div>
        <h4 class="font-weight-bold mb-3 border-bottom pb-3">Leave a Comment</h4>
        <form method="POST"  class="row">
             {% csrf_token %}
             {{ form }}         
             
             <div class="col-md-6">
               <br>
            <button type="submit" class="btn btn-primary w-100">Comment</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>


<section class="section">
  <div class="container">
    <div class="row">


      {% for x in blogs %}
        <div class="col-lg-4 col-sm-6 mb-4">
          <article class="card shadow">
            <img class="rounded card-img-top" src="{{x.image.url}}" style="height:300px;" alt="post-thumb">
            <div class="card-body">
              <h4 class="card-title"><a class="text-dark" href="blog-single.html">{{x.title}}</a>
              </h4>
              <p class="cars-text">{{x.small_description|truncatewords:10}}</p>
              <a href="{% url 'bourki:blogdetail' x.slug %}" class="btn btn-xs btn-primary">Read More</a>
            </div>
          </article>
        </div>
      {% endfor %}
    </div>
  </div>
</section>



<section class="section section-on-footer" data-background="{% static 'images/backgrounds/bg-dots.png' %}">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">BOURKI MDEV</h2>
      </div>
      <div class="col-lg-8 mx-auto">
        <div class="bg-white rounded text-center p-5 shadow-down">
          <h4 class="mb-80">WEB DEVLOPER</h4>
          
          <div class="col-md-4 text-center drag-lg-top">
            <div class="shadow-down mb-4">
              <img src="{% static 'images/about/author.jpg' %}" alt="author" class="img-fluid w-100 rounded-lg border-thick border-white">
            </div>
            <img src="{% static 'images/about/signature.png' %}" alt="signature" class="img-fluid">
            <h4>Bourki MDev</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<!-- jQuery -->
<script src="plugins/jQuery/jquery.min.js"></script>
<!-- Bootstrap JS -->
<script src="plugins/bootstrap/bootstrap.min.js"></script>
<!-- slick slider -->
<script src="plugins/slick/slick.min.js"></script>
<!-- filter -->
<script src="plugins/shuffle/shuffle.min.js"></script>

<!-- Main Script -->
<script src="js/script.js"></script>

</body>
</html>

{% endblock %}

templates/portfolio.html
{% extends 'index.html' %}
{% load static %}
{% block content %}<!DOCTYPE html>
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Kross | Portfolio Template</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="plugins/bootstrap/bootstrap.min.css">
  <!-- slick slider -->
  <link rel="stylesheet" href="plugins/slick/slick.css">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="plugins/themify-icons/themify-icons.css">

  <!-- Main Stylesheet -->
  <link href="css/style.css" rel="stylesheet">
  


</head>

<body>
  



<!-- page title -->
<section class="page-title bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="text-white font-tertiary">Portfolio</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{% static 'images/illustrations/page-title.png' %}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{% static 'images/illustrations/dots-cyan.png' %}" alt="illustrations" class="bg-shape-3">
  <img src="{% static 'images/illustrations/new.png' %}" alt="illustrations" class="bg-shape-4">
  <img src="{% static 'images/illustrations/leaf-yellow.png' %}" alt="illustrations" class="bg-shape-5">
  <img src="{% static 'images/illustrations/dots-group-cyan.png' %}" alt="illustrations" class="bg-shape-6">
  <img src="{% static 'images/illustrations/leaf-cyan-lg.png' %}" alt="illustrations" class="bg-shape-7">
</section>
<!-- /page title -->

<!-- portfolio -->
<section class="section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-12">
        <div class="btn-group btn-group-toggle justify-content-center d-flex" data-toggle="buttons">
          <label class="btn btn-sm btn-primary active">
            <input type="radio" name="shuffle-filter" value="all" checked="checked" />All
          </label>
          <label class="btn btn-sm btn-primary">
            <input type="radio" name="shuffle-filter" value="design" />UI/UX Design
          </label>
          <label class="btn btn-sm btn-primary">
            <input type="radio" name="shuffle-filter" value="branding" />BRANDING
          </label>
          <label class="btn btn-sm btn-primary">
            <input type="radio" name="shuffle-filter" value="illustration" />ILLUSTRATION
          </label>
        </div>
      </div>
    </div>
    <div class="row shuffle-wrapper">
      <div class="col-lg-4 col-6 mb-4 shuffle-item" data-groups="[&quot;design&quot;,&quot;illustration&quot;]">
        <div class="position-relative rounded hover-wrapper">
          <img src="{% static 'images/portfolio/item-1.png' %}" alt="portfolio-image" class="img-fluid rounded w-100 d-block">
          <div class="hover-overlay">
            <div class="hover-content">
              <a class="btn btn-light btn-sm" href="{% url 'bourki:projectdetail' %}">view project</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-6 mb-4 shuffle-item" data-groups="[&quot;branding&quot;]">
        <div class="position-relative rounded hover-wrapper">
          <img src="{% static 'images/portfolio/item-2.png' %}" alt="portfolio-image" class="img-fluid rounded w-100 d-block">
          <div class="hover-overlay">
            <div class="hover-content">
              <a class="btn btn-light btn-sm" href="{% url 'bourki:projectdetail' %}">view project</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-6 mb-4 shuffle-item" data-groups="[&quot;illustration&quot;]">
        <div class="position-relative rounded hover-wrapper">
          <img src="{% static 'images/portfolio/item-3.png' %}" alt="portfolio-image" class="img-fluid rounded w-100 d-block">
          <div class="hover-overlay">
            <div class="hover-content">
              <a class="btn btn-light btn-sm" href="{% url 'bourki:projectdetail' %}">view project</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-6 mb-4 shuffle-item" data-groups="[&quot;design&quot;,&quot;branding&quot;]">
        <div class="position-relative rounded hover-wrapper">
          <img src="{% static 'images/portfolio/item-6.png' %}" alt="portfolio-image" class="img-fluid rounded w-100 d-block">
          <div class="hover-overlay">
            <div class="hover-content">
              <a class="btn btn-light btn-sm" href="{% url 'bourki:projectdetail' %}">view project</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-6 mb-4 shuffle-item" data-groups="[&quot;illustration&quot;]">
        <div class="position-relative rounded hover-wrapper">
          <img src="{% static 'images/portfolio/item-8.png' %}" alt="portfolio-image" class="img-fluid rounded w-100 d-block">
          <div class="hover-overlay">
            <div class="hover-content">
              <a class="btn btn-light btn-sm" href="{% url 'bourki:projectdetail' %}">view project</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-6 mb-4 shuffle-item" data-groups="[&quot;design&quot;]">
        <div class="position-relative rounded hover-wrapper">
          <img src="{% static 'images/portfolio/item-5.png' %}" alt="portfolio-image" class="img-fluid rounded w-100 d-block">
          <div class="hover-overlay">
            <div class="hover-content">
              <a class="btn btn-light btn-sm" href="{% url 'bourki:projectdetail' %}">view project</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-6 mb-4 shuffle-item" data-groups="[&quot;branding&quot;]">
        <div class="position-relative rounded hover-wrapper">
          <img src="{% static 'images/portfolio/item-1.png' %}" alt="portfolio-image" class="img-fluid rounded w-100 d-block">
          <div class="hover-overlay">
            <div class="hover-content">
              <a class="btn btn-light btn-sm" href="{% url 'bourki:projectdetail' %}">view project</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-6 mb-4 shuffle-item" data-groups="[&quot;design&quot;,&quot;illustration&quot;,&quot;branding&quot;]">
        <div class="position-relative rounded hover-wrapper">
          <img src="{% static 'images/portfolio/item-3.png' %}" alt="portfolio-image" class="img-fluid rounded w-100 d-block">
          <div class="hover-overlay">
            <div class="hover-content">
              <a class="btn btn-light btn-sm" href="{% url 'bourki:projectdetail' %}">view project</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-6 mb-4 shuffle-item illustration" data-groups="[&quot;illustration&quot;]">
        <div class="position-relative rounded hover-wrapper">
          <img src="{% static 'images/portfolio/item-7.png' %}" alt="portfolio-image" class="img-fluid rounded w-100 d-block">
          <div class="hover-overlay">
            <div class="hover-content">
              <a class="btn btn-light btn-sm" href="{% url 'bourki:projectdetail' %}">view project</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /portfolio -->

<!-- clients -->
<section class="section bg-light">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">My Clients</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="client-logo-slider d-flex align-items-center">
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-1.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-2.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-3.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-4.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-5.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-1.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-2.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-3.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-4.png' %}" alt="client-logo"></a>
          <a href="#" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{% static 'images/clients-logo/client-logo-5.png' %}" alt="client-logo"></a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /clients -->

<!-- contact -->
<section class="section section-on-footer" data-background="{% static 'images/backgrounds/bg-dots.png' %}">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">BOURKI MDEV</h2>
      </div>
      <div class="col-lg-8 mx-auto">
        <div class="bg-white rounded text-center p-5 shadow-down">
          <h4 class="mb-80">WEB DEVLOPER</h4>
          
          <div class="col-md-4 text-center drag-lg-top">
            <div class="shadow-down mb-4">
              <img src="{% static 'images/about/author.jpg' %}" alt="author" class="img-fluid w-100 rounded-lg border-thick border-white">
            </div>
            <img src="{% static 'images/about/signature.png' %}" alt="signature" class="img-fluid">
            <h4>Bourki MDev</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /contact -->

<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- filter -->
<script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

{% endblock %}